### ISSUE TITLE
Using Qt from Xcode

### ISSUE THREAD

**Issue by PeterStano** [villevoutilainen/ProgrammingPrinciplesAndPracticeUsingQt#10]
Hi, I wonder if you could provide instructions on how to set Xcode to compile and link the files for MacOS users who are not eager to switch to a new IDE and would like to stay with Xcode (like me). Or how to set header and library information for the compiler/linker to do it from the command line (then I can figure it out for Xcode, hopefully).

I tried several ways [ 1) installing Qt according to your instructions and linking its frameworks 2) installing qt by homebrew and linking its libraries, 3) building static libraries from the Qt from source and linking them ], both from Xcode and from the command line and I failed in all these ways.

The farthest I could get was to get the Xcode to compile all cpp files from your bundle, with these settings for headers (?):

<img width="1167" alt="Screenshot 2024-10-09 at 13 49 55" src="https://github.com/user-attachments/assets/c91bab42-57db-4c07-9502-78e6a67cc1ee">

and for libraries (?):

<img width="1123" alt="Screenshot 2024-10-09 at 13 50 13" src="https://github.com/user-attachments/assets/6a7012d4-08bc-4f10-90d2-e87084a510be">

The files compile, but the linking phase fails with the following complaints from the linker:

<img width="1318" alt="Screenshot 2024-10-09 at 13 52 44" src="https://github.com/user-attachments/assets/64eab482-358d-4a24-832d-48a6c900cc7f">

I am sure I am doing something wrong, but I have no idea what. Your help is appreciated.

Best regards,
Peter

**Comment by villevoutilainen** [comment]
I'll see what I can do. Firing up the macbook.. :)

**Comment by PeterStano** [comment]
Ville, thank you, I appreciate your efforts!

In the meantime, I could not resist and googled random stuff further, and here is what I learned:

My original impression, from reading PPP3 and from previous requests of various software to "install Qt" was that Qt is a graphics library.  Now I see that Qt is an IDE. This confusion made the majority of material on the web making no sense to me previously: I thought I was looking for "how to use a library (Qt) from an IDE (Xcode); but I was kind of asking "how to use an IDE1 (Qt) from IDE2 (Xcode)", which makes much less sense.


Nevertheless, the most hopeful direction at the moment seems to be this single line:

qmake ~/src/myapp -spec macx-xcode

I saw it, and its variants, in several stackexchange discussions, and it is also on the Qt documentation page called (shame on me for not checking it initially) "Qt for macOS" (https://doc.qt.io/qt-6/macos.html)

Running the above command (qmake . -spec macx-xcode) from inside your files' directory indeed produces an Xcode project file ("UsingQt.xcodeproj") that can be opened by Xcode and which contains a host of path / header / library / framework settings. Unfortunately, the thing is too complex for my level of Xcode knowledge (which is poor) and still does not compile on my machine. However, the build errors' are now different, and there are warnings about versions (SDK vs Qt vs not sure what) compatibility, which probably are behind the failure.

I hope some of the above will be useful for you, should you decide to update your documentation. I am sure I won't be the only C++ beginner to benefit from that.



On Oct 11, 2024, at 2:35, Ville Voutilainen ***@***.***> wrote:



I'll see what I can do. Firing up the macbook.. :)

**Comment by villevoutilainen** [comment]
Qt is not an IDE. Qt is an application framework (not just a GUI framework). Qt Creator is the IDE.

I was distracted elsewhere today, didn't have time to check for solutions yet. I'll try again tomorrow. :)

**Comment by PeterStano** [comment]
Interesting!
Never heard of "application framework" before. I have been doing scientific programming for years, meaning compiling from terminal, programs that crunch numbers and at the end spit them into a text file. I never included any GUI element; it would be nice to have a window with a button saying "RUN" finally :)

...and potentially even something more useful in the longer outlook...



On Oct 11, 2024, at 10:22, Ville Voutilainen ***@***.***> wrote:



Qt is not an IDE. Qt is an application framework (not just a GUI framework). Qt Creator is the IDE.

I was distracted elsewhere today, didn't have time to check for solutions yet. I'll try again tomorrow. :)

**Comment by PeterStano** [comment]
Ville, sorry to bombard you, but I have the first success.
There is an alternative for the export of the Qt project into Xcode project: instead of qmake, use cmake.

running
Qt/Tools/CMake/CMake.app/Contents/bin/cmake -G Xcode path/to/your/directory/UsingQt

cmake has produced an xcodeproj file which can be opened and built successfully from Xcode. On the screenshot, you can see the source of the advice (SGaist on https://forum.qt.io/topic/145158/qt-6-5-for-macos-creating-xcode-project-for-macos-how/2) and my Xcode window.

I had to change the highlighted line in Wondow.cpp as the compiler complained about an implicit longint to int conversion. With that tiny change, I could get the "Hello World" window.

There are some runtime warnings/error (?) messages being produced (by I am not sure what), which you can see on the bottom right, but I would say overall, this is quite a progress.

I hope that with this, I can now return to PPP3 and its graphics chapters.

Thank you, your interest was encouraging in this initially hopelessly looking quest.


Best regards


***@***.***

**Comment by villevoutilainen** [comment]
Fantastic!

But did you forget to actually attach the screenshot?

**Comment by PeterStano** [comment]
sorry; it looks attached in my email client; trying with zip.



On Oct 11, 2024, at 14:52, Ville Voutilainen ***@***.***> wrote:



Fantastic!

But did you forget to actually attach the screenshot?

**Comment by villevoutilainen** [comment]
I don't think the attachments come through when responding to issue emails. Try adding them to comments on github.

Anyhoo, I have pushed a build fix for Xcode, for the long long int -> int conversion. And I do see some warnings about debug scripts and a failed stat operation. Those are indeed harmless.

**Comment by villevoutilainen** [comment]
FWIW, I had to use

`~/Qt/Tools/CMake/CMake.app/Contents/bin/cmake -DCMAKE_PREFIX_PATH=~/Qt/6.8.0/macos/lib/cmake  -G Xcode .`

to generate the xcode project. The prefix path tells cmake where to find the Qt cmake scripts.

**Comment by villevoutilainen** [comment]
And I'm not going to change the user manual for now. I much prefer Mac users using Qt Creator. But if more of them pop up that want to use Xcode, I'll first point them at the discussion in this issue, and if even more pop up, I'll update the manual. Thanks, @PeterStano for reporting the build problem, and for your efforts on figuring out how to make it work.

**Comment by PeterStano** [comment]
Ville, thanks!
For completeness, I am appending the screenshot described in the above.
<img width="2403" alt="Screenshot 2024-10-11 at 10 47 03" src="https://github.com/user-attachments/assets/17886cf2-57b2-498d-b8ae-eb13989d906f">
