### ISSUE TITLE
Comment mismatch on ifdef and endif

### ISSUE THREAD

**Issue by soheilarmin** [villevoutilainen/ProgrammingPrinciplesAndPracticeUsingQt#3]
https://github.com/villevoutilainen/ProgrammingPrinciplesAndPracticeUsingQt/blob/7dc3eafd93921eac75fef1c3c1abfe55fb0aca53/PPP/GUI_private.h#L82

#ifdef GUI_PRIVATE_GUARD does not match with #endif //GUI_GUARD

**Comment by villevoutilainen** [comment]
Fixed by https://github.com/villevoutilainen/ProgrammingPrinciplesAndPracticeUsingQt/commit/a4fe2ee2d6598e891eb47720b827d41a6a6993dd
